//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenUtensilsStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDKitchenUtensilsStore : DbContext
    {
        private static BDKitchenUtensilsStore _context;

        internal static BDKitchenUtensilsStore GetContext()
        {
            if (_context == null)
                _context = new BDKitchenUtensilsStore();
            return _context;
        }

        public BDKitchenUtensilsStore()
            : base("name=BDKitchenUtensilsStore")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Maker> Maker { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
    }
}
