//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenUtensilsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID_Tovar { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public string Ed { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<int> MaxRebate { get; set; }
        public Nullable<int> TovarMaker { get; set; }
        public Nullable<int> TovarVendor { get; set; }
        public Nullable<int> TovarType { get; set; }
        public Nullable<decimal> Rebate { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
