//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenUtensilsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID_Tovar { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public string Ed { get; set; }
        public decimal Sum { get; set; }
        public int MaxRebate { get; set; }
        public int TovarMaker { get; set; }
        public int TovarVendor { get; set; }
        public int TovarType { get; set; }
        public decimal Rebate { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Maker Maker { get; set; }
        public virtual Type Type { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
