//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenUtensilsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int ID_Vendor { get; set; }
        public string NameVendor { get; set; }
    }
}
